// This file is generated by npm run build:icons

export type IconName =
  | "arrow-back"
  | "awwwards"
  | "full-screen"
  | "fwa"
  | "github"
  | "linkedin"
  | "motion"
  | "next"
  | "quote"
  | "react"
  | "remix"
  | "tailwind"
  | "wild";
